### ISSUE TITLE
Cannot install Plugin elasticsearch-analysis-vietnamese version 7.12

### ISSUE THREAD

**Issue by newgate1999** [duydo/elasticsearch-analysis-vietnamese#100]
Hi all,
I want to add this plugin to elasticseach version 7.12.0. I changed the version in pom file and build project. Then I copied the jar file and compressed it into a zip file. but when installing the plugin it always gives this error. I don't know if I did it right.

sudo bin/elasticsearch-plugin install /usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip 
-> Installing /usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Failed installing /usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Rolling back /usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Rolled back /usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
A tool for managing installed elasticsearch plugins

I hope to hear from you soon.
Regard,

**Comment by duydo** [comment]
@newgate1999 Your installation command is missing a prefix `file://` in plugin path:
```sudo bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip```

**Comment by newgate1999** [comment]
thanks for your reply. but it throws new error. Can you help me check if the zip file is correct or not?

newgate@newgate-X510UQR:/usr/share/elasticsearch$ sudo bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip 
-> Installing file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Downloading file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
[=================================================] 100%   
-> Failed installing file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Rolling back file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
-> Rolled back file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.12.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-16293663515832790718/plugin-descriptor.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:173)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:786)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:845)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:245)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
newgate@newgate-X510UQR:/usr/share/elasticsearch$ ll
total 6340
drwxr-xr-x   7 root root    4096 Thg 5  18 08:19 ./
drwxr-xr-x 303 root root   12288 Thg 5  17 19:38 ../
drwxr-xr-x   2 root root    4096 Thg 4  18 09:42 bin/
-rw-r--r--   1 root root 5897815 Thg 5  18 08:19 elasticsearch-analysis-vietnamese-7.12.zip
drwxr-xr-x   9 root root    4096 Thg 4  18 09:42 jdk/
drwxr-xr-x   3 root root    4096 Thg 4  18 09:42 lib/
drwxr-xr-x  61 root root    4096 Thg 4  18 09:42 modules/
-rw-rw-r--   1 root root  545323 Thg 3  18 13:28 NOTICE.txt
drwxr-xr-x   3 root root    4096 Thg 5  18 09:52 plugins/
-rw-r--r--   1 root root    7263 Thg 3  18 13:27 README.asciidoc

my file zip: [link](https://drive.google.com/file/d/1yoMBUCjWWsIJklpPdDnb7i8TM9vRiBrJ/view?usp=sharing)

**Comment by newgate1999** [comment]
thanks for your reply. I'm resolved problem.
