### ISSUE TITLE
Offset Bug

### ISSUE THREAD

**Issue by vukhacbiet** [duydo/elasticsearch-analysis-vietnamese#114]
Đợt này lượng dữ liệu nhiều hơn, mỗi ngày mình thường bị BUG này 1  2 lần, đúng lúc cao điểm dữ liệu đổ về nhiều, data thì y nhau, đột nhiên bị bug offset này, mong được giúp đỡ.

```sh
{"type": "server", "timestamp": "2021-11-25T01:10:26,553+0000", "level": "DEBUG", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "docker-cluster", "node.name": "15abb974bd88", "cluster.uuid": "u7EANW9CRmqOP0oyAdyeEw", "node.id": "itIX8UMtSuary_TkzgN0ug",  "message": "[order_item_ingredients][0] failed to execute bulk item (index) index {[order_item_ingredients][_doc][12077], source[{\"store_id\":10,\"order_item_id\":19358,\"ingredient_data_id\":15,\"ingredient_group_id\":39,\"item_data_id\":56,\"store_item_id\":645,\"store_menu_group_id\":127,\"ingredient_name\":\"Size M\",\"ingredient_group_name\":\"Size\",\"group_mandatory\":true,\"reportable\":true,\"item_name\":\"Fup.Cafe S\\u1eefa \\u0110\\u00e1\",\"item_group_name\":\"FREE UPSIZE\",\"price\":0,\"discount\":0,\"base_price\":10000,\"quantity\":1,\"ordered_at\":\"2021-11-25 08:10:26\",\"period_id\":null,\"shift_code\":null,\"shift_staff_code\":null,\"updated_at\":\"2021-11-25T01:10:26.000000Z\",\"created_at\":\"2021-11-25T01:10:26.000000Z\",\"id\":12077}]}" , 
"stacktrace": ["java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset; got startOffset=-1,endOffset=4",
"at org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.setOffset(PackedTokenAttributeImpl.java:113) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.analysis.vi.VietnameseTokenizer.incrementToken(VietnameseTokenizer.java:82) ~[?:?]",
"at org.apache.lucene.analysis.icu.ICUNormalizer2Filter.incrementToken(ICUNormalizer2Filter.java:80) ~[?:?]",
"at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:812) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
"at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1129) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1074) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:904) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:792) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:764) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:721) ~[elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:256) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:159) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:191) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77) [elasticsearch-7.3.1.jar:7.3.1]",
"at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:923) [elasticsearch-7.3.1.jar:7.3.1]",

```

**Comment by dangtoanphat** [comment]
Mình cũng đang gặp issue tương tự, cho hỏi là bạn đã có cách giải quyết chưa?

**Comment by duydo** [comment]
@vukhacbiet Issue này đã fixed trong release mới nhất v7.17.1 nha
