### ISSUE TITLE
Error testVietnameseTokenizer(org.elasticsearch.index.analysis.VietnameseAnalysisTests)

### ISSUE THREAD

**Issue by BlankS2** [duydo/elasticsearch-analysis-vietnamese#126]
Em chào anh
Hiện tại thì e đang bị lỗi ngay bước mvn package của elasticsearch-analysis-vietnamese
Phần coccoc-tokenize thì em đã test bằng terminal rồi ạ
Em đang dùng elastic bản 8.2.2
`[ERROR] testVietnameseTokenizer(org.elasticsearch.index.analysis.VietnameseAnalysisTests)  Time elapsed: 0.019 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/BaseTokenStreamTestCase
	at org.elasticsearch.index.analysis.VietnameseAnalysisTests.testVietnameseTokenizer(VietnameseAnalysisTests.java:100)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.BaseTokenStreamTestCase
	at org.elasticsearch.index.analysis.VietnameseAnalysisTests.testVietnameseTokenizer(VietnameseAnalysisTests.java:100)
`

**Comment by duydo** [comment]
@BlankS2 Plugin anh chưa hỗ trợ Elasticsearch 8.x nha em, để anh thu xếp thời gian làm.

**Comment by BlankS2** [comment]
> @BlankS2 Plugin anh chưa hỗ trợ Elasticsearch 8.x nha em, để anh thu xếp thời gian làm.

Dạ em cảm ơn anh
