### ISSUE TITLE
BUILD FAILURE VietnameseAnalyzerProvider.java:[33,9]

### ISSUE THREAD

**Issue by vukhacbiet** [duydo/elasticsearch-analysis-vietnamese#137]
Mình build bị lỗi như sau, xin nhờ giúp đỡ:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch-analysis-vietnamese: Compilation failure: Compilation failure:
[ERROR] /Users/apple/Documents/CODE/untitled folder 2/elasticsearch-analysis-vietnamese/src/main/java/org/elasticsearch/index/analysis/VietnameseAnalyzerProvider.java:[33,9] constructor AbstractIndexAnalyzerProvider in class org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider<T> cannot be applied to given types;
[ERROR]   required: org.elasticsearch.index.IndexSettings,java.lang.String,org.elasticsearch.common.settings.Settings
[ERROR]   found:    java.lang.String,org.elasticsearch.common.settings.Settings
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /Users/apple/Documents/CODE/untitled folder 2/elasticsearch-analysis-vietnamese/src/main/java/org/elasticsearch/index/analysis/VietnameseStopTokenFilterFactory.java:[22,9] constructor AbstractTokenFilterFactory in class org.elasticsearch.index.analysis.AbstractTokenFilterFactory cannot be applied to given types;
[ERROR]   required: org.elasticsearch.index.IndexSettings,java.lang.String,org.elasticsearch.common.settings.Settings
[ERROR]   found:    java.lang.String,org.elasticsearch.common.settings.Settings
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by vukhacbiet** [comment]
Mình đang build trên mac M1, openjdk 17.0.7

**Comment by vukhacbiet** [comment]
Output đây nha:
[INFO]
[INFO] The following files have been resolved:
[INFO]    org.apache.lucene:lucene-test-framework:jar:9.5.0:test
[INFO]    io.netty:netty-resolver:jar:4.1.86.Final:test
[INFO]    org.apache.lucene:lucene-highlighter:jar:9.5.0:provided
[INFO]    com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    org.elasticsearch:elasticsearch:jar:8.7.0:provided
[INFO]    org.lz4:lz4-java:jar:1.8.0:provided
[INFO]    io.netty:netty-codec:jar:4.1.86.Final:test
[INFO]    org.apache.lucene:lucene-grouping:jar:9.5.0:provided
[INFO]    org.elasticsearch:elasticsearch-cli:jar:8.7.0:provided
[INFO]    org.mockito:mockito-core:jar:4.4.0:test
[INFO]    io.netty:netty-transport-native-unix-common:jar:4.1.86.Final:test
[INFO]    com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO]    org.apache.lucene:lucene-queries:jar:9.5.0:provided
[INFO]    io.netty:netty-transport:jar:4.1.86.Final:test
[INFO]    org.elasticsearch.plugin:elasticsearch-plugin-analysis-api:jar:8.7.0:provided
[INFO]    org.apache.lucene:lucene-core:jar:9.5.0:provided
[INFO]    org.apache.lucene:lucene-memory:jar:9.5.0:provided
[INFO]    org.elasticsearch:elasticsearch-secure-sm:jar:8.7.0:provided
[INFO]    io.netty:netty-handler:jar:4.1.86.Final:test
[INFO]    org.elasticsearch:elasticsearch-lz4:jar:8.7.0:provided
[INFO]    commons-codec:commons-codec:jar:1.15:test
[INFO]    org.apache.lucene:lucene-backward-codecs:jar:9.5.0:provided
[INFO]    com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    net.java.dev.jna:jna:jar:5.10.0:provided
[INFO]    org.apache.lucene:lucene-misc:jar:9.5.0:provided
[INFO]    com.carrotsearch:hppc:jar:0.8.1:provided
[INFO]    org.elasticsearch:elasticsearch-core:jar:8.7.0:provided
[INFO]    commons-logging:commons-logging:jar:1.2:test
[INFO]    org.elasticsearch:elasticsearch-x-content:jar:8.7.0:provided
[INFO]    org.apache.lucene:lucene-suggest:jar:9.5.0:provided
[INFO]    com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.17.2:test
[INFO]    org.apache.httpcomponents:httpcore:jar:4.4.13:test
[INFO]    org.elasticsearch.test:framework:jar:8.7.0:test
[INFO]    com.google.guava:guava:jar:31.1-jre:compile
[INFO]    com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    org.elasticsearch:elasticsearch-geo:jar:8.7.0:provided
[INFO]    org.apache.httpcomponents:httpclient:jar:4.5.13:test
[INFO]    org.apache.logging.log4j:log4j-core:jar:2.17.2:test
[INFO]    org.hamcrest:hamcrest:jar:2.1:test
[INFO]    com.tdunning:t-digest:jar:3.2:provided
[INFO]    org.hdrhistogram:HdrHistogram:jar:2.1.9:provided
[INFO]    org.elasticsearch.plugin:elasticsearch-plugin-api:jar:8.7.0:provided
[INFO]    org.elasticsearch:mocksocket:jar:1.2:test
[INFO]    org.apache.lucene:lucene-queryparser:jar:9.5.0:provided
[INFO]    io.netty:netty-buffer:jar:4.1.86.Final:test
[INFO]    org.apache.lucene:lucene-join:jar:9.5.0:provided
[INFO]    io.netty:netty-codec-http:jar:4.1.86.Final:test
[INFO]    io.netty:netty-common:jar:4.1.86.Final:test
[INFO]    org.apache.lucene:lucene-sandbox:jar:9.5.0:provided
[INFO]    org.elasticsearch.plugin:transport-netty4:jar:8.7.0:test
[INFO]    org.elasticsearch:elasticsearch-ssl-config:jar:8.7.0:test
[INFO]    net.sf.jopt-simple:jopt-simple:jar:5.0.2:provided
[INFO]    org.elasticsearch.client:elasticsearch-rest-client:jar:8.7.0:test
[INFO]    org.objenesis:objenesis:jar:3.2:test
[INFO]    org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO]    junit:junit:jar:4.12:test
[INFO]    org.apache.lucene:lucene-codecs:jar:9.5.0:test
[INFO]    com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.8.0:test
[INFO]    net.bytebuddy:byte-buddy:jar:1.12.9:test
[INFO]    co.elastic.logging:log4j2-ecs-layout:jar:1.2.0:provided
[INFO]    co.elastic.logging:ecs-logging-core:jar:1.2.0:provided
[INFO]    org.elasticsearch:elasticsearch-plugin-classloader:jar:8.7.0:provided
[INFO]    org.apache.httpcomponents:httpcore-nio:jar:4.4.13:test
[INFO]    org.apache.httpcomponents:httpasyncclient:jar:4.1.5:test
[INFO]    org.elasticsearch:elasticsearch-logging:jar:8.7.0:provided
[INFO]    org.apache.lucene:lucene-analysis-common:jar:9.5.0:provided
[INFO]

**Comment by duydo** [comment]
> @duydo xin lỗi mình chưa mô tả kỹ: Mình dùng branch master nhưng đang muốn build cho ES 7.17.1, khi build 8.7.0 thì build được. Dùng branch 7.x thì build ok, nhưng khi install xong restart ES lỗi không lên như #133

Nhánh master hiện tại cho v8.7 không compatible với v7.x. Để build cho 7.17.1 bạn dùng nhánh [7.16-7.17.1](https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/7.16-7.17.1)
Gần đây ES hay break APIs giữa các versions, mình cần phải test với từng version để đảm bảo compatible, nhánh 7.x hiện tại chỉ work cho 7.17.5 - 7.17.10. Để có thời gian mình tách ra các versions nhỏ hơn.

**Comment by vukhacbiet** [comment]
> > @duydo xin lỗi mình chưa mô tả kỹ: Mình dùng branch master nhưng đang muốn build cho ES 7.17.1, khi build 8.7.0 thì build được. Dùng branch 7.x thì build ok, nhưng khi install xong restart ES lỗi không lên như #133
> 
> Nhánh master hiện tại cho v8.7 không compatible với v7.x. Để build cho 7.17.1 bạn dùng nhánh [7.16-7.17.1](https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/7.16-7.17.1) Gần đây ES hay break APIs giữa các versions, mình cần phải test với từng version để đảm bảo compatible, nhánh 7.x hiện tại chỉ work cho 7.17.5 - 7.17.10. Để có thời gian mình tách ra các versions nhỏ hơn.

Mình vừa build từ nhánh này, xong cài lên vẫn lỗi #133 
![Screen Shot 2023-05-11 at 08 39 13](https://github.com/duydo/elasticsearch-analysis-vietnamese/assets/43400653/12bdb980-3df2-4ee1-b14b-a7f7386c58fb)
`2023-05-11 07:32:38 "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Could not find plugin class [org.elasticsearch.plugin.analysis.vi.AnalysisVietnamesePlugin]]; nested: ClassNotFoundException[org.elasticsearch.plugin.analysis.vi.AnalysisVietnamesePlugin];",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "Caused by: org.elasticsearch.ElasticsearchException: Could not find plugin class [org.elasticsearch.plugin.analysis.vi.AnalysisVietnamesePlugin]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:779) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:738) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.node.Node.<init>(Node.java:411) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "... 6 more",
2023-05-11 07:32:38 "Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.vi.AnalysisVietnamesePlugin",
2023-05-11 07:32:38 "at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]",
2023-05-11 07:32:38 "at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]",
2023-05-11 07:32:38 "at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[?:?]",
2023-05-11 07:32:38 "at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]",
2023-05-11 07:32:38 "at java.lang.Class.forName0(Native Method) ~[?:?]",
2023-05-11 07:32:38 "at java.lang.Class.forName(Class.java:467) ~[?:?]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:777) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:738) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.node.Node.<init>(Node.java:411) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.1.jar:7.17.1]",
2023-05-11 07:32:38 "... 6 more"] }`

**Comment by vukhacbiet** [comment]
Mình đã build đc và run được nha, cảm ơn @duydo nhiều nha.
