### ISSUE TITLE
Cannot Index Document on 2.2.0

### ISSUE THREAD

**Issue by dripp1** [duydo/elasticsearch-analysis-vietnamese#14]
Hi,
I installed version 2.2.0 of the plugin into elasticsearch 2.2.0 and installation (and also index creation) worked fine. For this index I set the default analyzer like this:

```
"default": {
  "type": "vi_analyzer"
}
```

Now, when I try to index a simple document like this:

```
PUT /vi_index/system/1
{
  "test": "15"
}
```

I get error:

```
{
	"error" : {
		"root_cause" : [{
				"type" : "remote_transport_exception",
				"reason" : "[Kasper Cole][127.0.0.1:9300][indices:data/write/index[p]]"
			}
		],
		"type" : "null_pointer_exception",
		"reason" : null
	},
	"status" : 500
}
```

and when I run the same functionality from Java, I get a more detailed error:

```
java.lang.NullPointerException
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(VietnameseTokenizer.java:74)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(VietnameseTokenizer.java:62)
	at org.apache.lucene.analysis.vi.VietnameseAnalyzer.createComponents(VietnameseAnalyzer.java:83)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:176)
	at org.apache.lucene.document.Field.tokenStream(Field.java:562)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:607)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:539)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:468)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:567)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:65)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:595)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:263)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
```

Can you please check this issue?
Thanks!

**Comment by duydo** [comment]
Thanks for your report, I will try to fix in several days.

**Comment by knd** [comment]
Hi @duydo , any update on this or ways to work around?

**Comment by apueee** [comment]
Hi @duydo is there any update on this issue? I'm getting same error and can't skip the error

**Comment by dripp1** [comment]
Hi @duydo any chance of fixing this any time soon?
Thank you.

**Comment by duydo** [comment]
Hi all, I'm working on this issue. I hope it can be fixed very soon.

**Comment by duydo** [comment]
@knd @apueee @dripp1: I've just fixed the issue, please re-install https://dl.dropboxusercontent.com/u/1598491/elasticsearch-analysis-vietnamese-0.2.2.zip

**Comment by dripp1** [comment]
Thank you!!
