### ISSUE TITLE
build plugin 8.11.3 lỗi ạ

### ISSUE THREAD

**Issue by vuchiencong** [duydo/elasticsearch-analysis-vietnamese#149]
a Duy ơi cho em hỏi chút ạ, em build dùng es 8.11.3 thì có lỗi này ạ
9.117 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                                                                                                                                                                             
9.117 @     WARNING: plugin requires additional permissions     @
9.117 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
9.118 * java.lang.RuntimePermission accessClassInPackage.sun.misc
9.118 * java.lang.RuntimePermission accessDeclaredMembers
9.118 * java.lang.RuntimePermission loadLibrary.coccoc_tokenizer_jni
9.118 * java.lang.reflect.ReflectPermission suppressAccessChecks
9.118 See https://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
9.118 for descriptions of what these permissions allow and the associated risks.
9.119 Continue with installation? [y/N]
9.119 -> Failed installing file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-8.11.3.zip
9.120 -> Rolling back file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-8.11.3.zip
9.126 -> Rolled back file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-8.11.3.zip
9.126 Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
9.127 	at org.elasticsearch.cli.Terminal.read(Terminal.java:94)
9.127 	at org.elasticsearch.cli.Terminal.readText(Terminal.java:101)
9.128 	at org.elasticsearch.plugins.cli.PluginSecurity.prompt(PluginSecurity.java:80)
9.128 	at org.elasticsearch.plugins.cli.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:72)
9.128 	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:922)
9.129 	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:254)
9.129 	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
9.129 	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
9.129 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
9.129 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
9.130 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
9.130 	at org.elasticsearch.cli.Command.main(Command.java:50)
9.130 	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
------
Dockerfile:8
--------------------
   7 |     COPY elasticsearch-analysis-vietnamese-8.11.3.zip /usr/share/elasticsearch/
   8 | >>> RUN cd /usr/share/elasticsearch && \
   9 | >>>   bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-8.11.3.zip && \
  10 | >>>   bin/elasticsearch-plugin install analysis-icu
  11 |

bản 5.3.1 em test thì vẫn chạy bình thường k có lỗi này

**Comment by duydo** [comment]
Anh chưa test với v8.11.3, để anh test xem thử.

**Comment by nvttrong2511** [comment]
Lỗi đó đã fix được chưa ae ơi
