### ISSUE TITLE
Lỗi khi search elasticsearch

### ISSUE THREAD

**Issue by khanhoatink4** [duydo/elasticsearch-analysis-vietnamese#16]
Sau khi đánh index và insert dữ liệu vào, khi search thì vẫn ra kết quả nhưng nhìn log thì có lỗi này:

_> java.security.AccessControlException: access denied ("java.io.FilePermission" "tokenizer.log.lck" "write")
> 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
> 	at java.security.AccessController.checkPermission(AccessController.java:884)
> 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
> 	at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
> 	at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:247)
> 	at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136)
> 	at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
> 	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:175)
> 	at java.nio.channels.FileChannel.open(FileChannel.java:287)
> 	at java.nio.channels.FileChannel.open(FileChannel.java:335)
> 	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
> 	at java.util.logging.FileHandler.<init>(FileHandler.java:292)
> 	at vn.hus.nlp.tokenizer.Tokenizer.createLogger(Tokenizer.java:167)
> 	at vn.hus.nlp.tokenizer.Tokenizer.<init>(Tokenizer.java:134)
> 	at vn.hus.nlp.tokenizer.TokenizerProvider.<init>(TokenizerProvider.java:58)
> 	at vn.hus.nlp.tokenizer.TokenizerProvider.getInstance(TokenizerProvider.java:108)_
_

`Caused by: java.lang.NullPointerException
	at vn.hus.nlp.tokenizer.Tokenizer.tokenize(Tokenizer.java:251)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.tokenize(VietnameseTokenizer.java:88)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.reset(VietnameseTokenizer.java:141)
	at org.apache.lucene.analysis.CachingTokenFilter.reset(CachingTokenFilter.java:58)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:222)
	at org.apache.lucene.util.QueryBuilder.createBooleanQuery(QueryBuilder.java:87)
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:176)
	at org.elasticsearch.index.search.MultiMatchQuery.parseAndApply(MultiMatchQuery.java:54)
	at org.elasticsearch.index.search.MultiMatchQuery.access$000(MultiMatchQuery.java:41)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.parseGroup(MultiMatchQuery.java:120)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.buildGroupedQueries(MultiMatchQuery.java:111)
`
Anh có biết nguyên nhân do đâu không ạ? Em cảm ơn!

**Comment by duydo** [comment]
Cái này là lỗi do thư viện VnTokenizer không có quyền ghi log xuống file, không ảnh hưởng gì đến việc index và search nhé em.

**Comment by hovanhon** [comment]
dear Duy Đỗ
xin hỏi có cách nào fix không nếu index khoảng 5 triệu index thì nó quăng ra lượng log rất lớn do lỗi trên gây ra.

**Comment by homer2017** [comment]
khi em sử dụng elasticsearch-analysis-vietnamese cũng bị lỗi như trên và khi search tiếng Việt không dấu lại lúc được lúc không? anh có thể chỉ ra cách khắc phục lỗi trên giúp ko ạ? cám ơn anh!
