### ISSUE TITLE
Exception Khi Truy Vấn Dữ Liệu

### ISSUE THREAD

**Issue by khoimt** [duydo/elasticsearch-analysis-vietnamese#23]
Em chào anh, rất cảm ơn về bộ thư viện hữu ích. 

Hiện tại em đang chạy thử nghiệm thư viện của anh tuy nhiên mỗi lần truy vấn các node es em thử nghiệm đề có Exception bắn ra, lỗi bắn ra khá ngẫu nhiên với từng node mặc dù query giống nhau. Anh có thể xem ảnh em đính kèm. Có thể vì lỗi này mà kết quả trả ra cho mỗi query cũng không giống nhau.

Em đang chạy thử với ES 2.4.4 lucene  5.5.2,  OpenJDK 8, Debian 8 với khoảng 200 nghìn dữ liệu địa chỉ. Nếu anh có thời gian và cần tái hiện lại lỗi có thể liên hệ với em qua mail khoimt47ATgmail.com để lấy dữ liệu mẫu. Em cũng muốn debug nhưng chưa biết nên bắt đầu từ đâu.

Cảm ơn anh.

http://imgur.com/a/oJZ9r
http://imgur.com/a/xJE47

Elasticsearch error log:

[DEBUG][action.search            ] [Chase Stein] [address-mapping-de][2], node[Okfd0cdjTGasSGietUUG8g], [P], v[2], s[STARTED], a[id=vqeDdbV-SqmPJlUfa1r9wQ]: Failed to execute [org.elasticsearch.action.search.SearchRequest@51525c16] lastShard [true]
RemoteTransportException[[Chase Stein][10.0.2.15:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{
   "query": {
      "query_string": {
         // "fields" : ["pn", "dn", "pn.folded", "dn.folded"],
         "query": "12 2A đường 18 pid:126 did:1074",
         "analyzer": "vi_analyzer"
      }
   }
}
]]; nested: NullPointerException;
Caused by: SearchParseException[failed to parse search source [{
   "query": {
       
      "query_string": {
         // "fields" : ["pn", "dn", "pn.folded", "dn.folded"],
         "query": "12 2A đường 18 pid:126 did:1074",
         "analyzer": "vi_analyzer"
      }
   }
}
]]; nested: NullPointerException;
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:873)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by khoimt** [comment]
Hi anh,

có vẻ vấn đề sẽ phát sinh khi dữ liệu được lưu trên nhiều shards, em điều chỉnh số shard = 1 thì không còn lỗi nữa. Em không nhiều kinh nghiệm code java nên gặp khá nhiều khó khăn để debug, hiện tại xem được dữ liệu input  khi đẩy vào hàm VietnameseTokenizer::tokenize dẫn đến lỗi có cách nào để debug watch được tại thời điểm đấy không anh.

Thanks,

**Comment by duydo** [comment]
@khoimt Có vẻ như cái lib VnTokenizer không thread-safe, để cuối tuần này anh kiểm tra thêm nhé.

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37

**Comment by nguyentienlong** [comment]
Anh @duydo oi, em cũng bị lỗi tương tự, chắc tạm thời em chỉnh lại shard = 1 như bạn @khoimt suggest thử xem sao.
