### ISSUE TITLE
install plugin es-analysis với docker es 5.3.1

### ISSUE THREAD

**Issue by khs123** [duydo/elasticsearch-analysis-vietnamese#60]
Hi 
Mình có tìm hiểu và muốn sử dụng es để phục vụ việc search dữ liệu tiếng viết hệ thống mình, mình  thì dùng docker để chạy es. Tuy nhiên khi cài plugin thì báo lỗi
`Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:373)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:207)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
`
Bạn nào có thể giúp mình fix được lỗi này ko ạ
Cám ơn

**Comment by duydo** [comment]
@khs123 Bạn mô tả cụ thể hơn quá trình cài đặt plugin nhé.

**Comment by khs123** [comment]
Mình đã fix được lỗi đó rồi :D
