### ISSUE TITLE
The issue for 7.3.1 version when build new image on docker

### ISSUE THREAD

**Issue by vknvnn** [duydo/elasticsearch-analysis-vietnamese#65]
### In the my dockerfile:
FROM elasticsearch:7.3.1

COPY elasticsearch-analysis-vietnamese-7.3.1.zip /usr/share/elasticsearch/

RUN cd /usr/share/elasticsearch && \
  bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.3.1.zip && \
  bin/elasticsearch-plugin install analysis-icu

### When I run:
docker build -t elasticsearch-vi:7.3.1 .
Sending build context to Docker daemon  10.46MB
Step 1/3 : FROM elasticsearch:7.3.1
 ---> 3d3aa92f641f
Step 2/3 : COPY elasticsearch-analysis-vietnamese-7.3.1.zip /usr/share/elasticsearch/
 ---> Using cache
 ---> 2dd1b5083161
Step 3/3 : RUN cd /usr/share/elasticsearch &&   bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.3.1.zip &&   bin/elasticsearch-plugin install analysis-icu
 ---> Running in f498d966d8c9
-> Downloading file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.3.1.zip
[=================================================] 100%?? 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission *#plus read,write
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
	at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:173)
	at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
	at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:67)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:811)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c cd /usr/share/elasticsearch &&   bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.3.1.zip &&   bin/elasticsearch-plugin install analysis-icu' returned a non-zero code: 1

**I will be tried with 5.3.1 version, it's work, I think this is a bug.**

**Comment by phamducmanh1989** [comment]
Can you try this:
`FROM elasticsearch:7.3.1

COPY elasticsearch-analysis-vietnamese-7.3.1.zip /usr/share/elasticsearch/

RUN cd /usr/share/elasticsearch && 
bin/elasticsearch-plugin install --batch file:///usr/share/elasticsearch/elasticsearch-analysis-vietnamese-7.3.1.zip && 
bin/elasticsearch-plugin install analysis-icu`

**Comment by duydo** [comment]
@vknvnn Can you please try to install plugin with `batch mode` with option `--batch` as @phamducmanh1989 suggested? If it still does not work, try `--force` option.

**Comment by vknvnn** [comment]
many thanks to @duydo, @phamducmanh1989
