### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by bkstorm** [duydo/elasticsearch-analysis-vietnamese#68]
Hi.
I use Logstash to synchronize data from Postgresql to Elasticsearch.
I encounter an error.
Here is the error log:
```
elasticsearch_1  | {"type": "server", "timestamp": "2019-09-19T09:34:58,606+0000", "level": "DEBUG", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "docker-cluster", "node.name": "9180755148ed", "cluster.uuid": "2cOGvFfiS7a6grJYHe8amQ", "node.id": "8QJJkf7IRAeVCu7w9uhoXA",  "message": "[products_vi][0] failed to execute bulk item (index) index {[products_vi][_doc][88423], source[{\"description\":\"- Kem dưỡng massage nâng tone làm sạch bụi mịn, bụi vàng, làm sạch các sản phẩm make up, loại bỏ da chết, lấy hết bã nhờn và dầu thừa trên da\\n- Nhờ phức hợp chiết xuất từ chanh, hiệu quả làm sáng da, lấy sạch bã nhờn gấp 3 lần\\n- Ngoài ra còn có 11 thành phần thực vật có khả năng làm sạch da\\n\\n* Hướng dẫn sử dụng:\\n- Sau khi rửa mặt, lấy một lượng vừa phải lên mặt\\n- Thoa đều trên da theo hình tròn, mát - xa khoảng 1-2 phút\\n- Dùng khăn giấy/bông tẩy trang lau sạch da và bắt dầu bước dưỡng sau đó\","name\":\"Skin Tone Up Massage Cream 3x\",\"@timestamp\":\"2019-09-19T09:24:58.934Z\"}]}" , 
elasticsearch_1  | "stacktrace": ["java.lang.StringIndexOutOfBoundsException: String index out of range: -1",
elasticsearch_1  | "at java.lang.StringLatin1.charAt(StringLatin1.java:47) ~[?:?]",
elasticsearch_1  | "at java.lang.String.charAt(String.java:702) ~[?:?]",
elasticsearch_1  | "at me.duydo.vi.Tokenizer.tokenize(Tokenizer.java:105) ~[?:?]",
elasticsearch_1  | "at org.apache.lucene.analysis.vi.VietnameseTokenizer.tokenize(VietnameseTokenizer.java:57) ~[?:?]",
elasticsearch_1  | "at org.apache.lucene.analysis.vi.VietnameseTokenizer.incrementToken(VietnameseTokenizer.java:66) ~[?:?]",
elasticsearch_1  | "at org.apache.lucene.analysis.icu.ICUNormalizer2Filter.incrementToken(ICUNormalizer2Filter.java:80) ~[?:?]",
elasticsearch_1  | "at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:812) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]",
elasticsearch_1  | "at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1129) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1074) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:904) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:792) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:764) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:721) ~[elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:256) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:159) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:191) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:923) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:398) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:316) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$15(IndexShard.java:2606) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2580) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:864) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:312) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:275) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:703) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) [?:?]"] }
```

Here is my index `products_vi`:
```
curl -XPUT -H 'Content-Type:application/json' -u elastic:changeme "localhost:9200/products_vi?pretty" -d '
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 1,
      "analysis": {
        "analyzer": {
          "vi_analyzer": {
            "tokenizer": "vi_tokenizer",
            "char_filter": [
              "html_strip"
            ],
            "filter": [
              "icu_folding"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "name": {
        "type":"text",
        "analyzer": "vi_analyzer"
      },
      "description": {
        "type":"text",
        "analyzer": "vi_analyzer"
      }
    }
  }
}
'
```

I'm using:
- Elasticsearch version 7.3.1.
- elasticsearch-analysis-vetnamese-7.3.1

**Comment by duydo** [comment]
This bug relates to issue #67.

**Comment by meodemsao** [comment]
i have same issue

**Comment by hanhfgia** [comment]
Maybe fix at
https://github.com/duydo/vn-nlp-libraries/blob/b687d5f11392049165ea166c2fea8431caf0262a/nlp-parent/nlp-tokenizer/src/main/java/me/duydo/vi/Tokenizer.java#L105

`
if (tokenEnd >= 0 && tokenEnd < line.length()) {
...
}
`

**Comment by undergrowthlinear** [comment]
this code can fix multi space bug

Code:
org.apache.lucene.analysis.vi.VietnameseTokenizer#incrementToken line 81
    final int start = inputText.indexOf(word.getText(), i);
   offsetAtt.setOffset(correctOffset(start), offset = correctOffset(start + length));

change to 
               final int start = inputText.indexOf(word.getText(), offset);
                int startChange = start;
                if (start < 0) {
                    // fix multi space bug
                    // https://github.com/duydo/elasticsearch-analysis-vietnamese/issues/68
                    if (word.getText() != null) {
                        startChange = inputText.indexOf(word.getText().split(" ")[0], offset);
                    }

                }
                offsetAtt.setOffset(correctOffset(start < 0 ? startChange : start),
                    offset = correctOffset((start < 0 ? startChange : start) + length));




Test Code:
public class VietnameseAnalysisTokenTest extends ESTestCase {

    public void testVietnameseTokenizer() throws IOException {
        inputToken("nguyễn văn bé nhỏ", new String[] {"nguyễn", "văn", "bé nhỏ"});
    }

    public void testVietnameseTokenizerSpace() throws IOException {
        inputToken("nguyễn  văn  bé  nhỏ", new String[] {"nguyễn", "văn", "bé nhỏ"});
    }

    public void testVietnameseTokenizerSpace3() throws IOException {
        inputToken("nguyễn   văn   bé   nhỏ  ", new String[] {"nguyễn", "văn", "bé nhỏ"});
    }

    private void inputToken(String inputText, String[] expectArray) throws IOException {
        TestAnalysis analysis = VietnameseAnalysisTest.createTestAnalysis();
        NamedAnalyzer analyzer = analysis.indexAnalyzers.get("vi_analyzer");
        assertNotNull(analyzer);

        TokenStream ts = analyzer.analyzer().tokenStream("test", inputText);
        CharTermAttribute term = ts.addAttribute(CharTermAttribute.class);
        ts.reset();
        for (String expected : expectArray) {
            assertThat(ts.incrementToken(), equalTo(true));
            assertThat(term.toString(), equalTo(expected));
            // System.out.println(term.toString());
        }
        assertThat(ts.incrementToken(), equalTo(false));
    }

}

**Comment by duydo** [comment]
Hi @undergrowthlinear, can you please make PR for this? Thanks.
