### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by anhvudg** [duydo/elasticsearch-analysis-vietnamese#7]
Hi duydo,

I'm studying about Vietnamese tokenizing. I installed plugin version 0.1.1 with the latest ES. When using vi_analyzer with the sample suggester at http://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-suggesters-phrase.html, I got 2 NPE (tokenizer provider cannt get an instance). Here they are:

```java
java.lang.NullPointerException
	at vn.hus.nlp.tokenizer.Tokenizer.tokenize(Tokenizer.java:251)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.tokenize(VietnameseTokenizer.java:83)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.reset(VietnameseTokenizer.java:141)
	at org.apache.lucene.analysis.TokenFilter.reset(TokenFilter.java:70)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:126)
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker.getCorrections(NoisyChannelSpellChecker.java:66)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:99)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:53)
	at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:42)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:85)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:74)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:170)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:286)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:297)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

và đoạn NPE thứ 2

```java
java.lang.NullPointerException
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(VietnameseTokenizer.java:74)
	at org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(VietnameseTokenizer.java:62)
	at org.elasticsearch.indices.analysis.VietnameseIndicesAnalysis$1.create(VietnameseIndicesAnalysis.java:53)
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:83)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:113)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:113)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:144)
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker.tokenStream(NoisyChannelSpellChecker.java:143)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:96)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:53)
	at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:42)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:85)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:74)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:170)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:286)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:297)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by duydo** [comment]
Currently the plugin does not support ES v1.5, I have not upgraded to ES 1.5 yet.

**Comment by DienNM** [comment]
I get the same error when try to use ES 1.7.4 with your plugin at 0.1.7
