### ISSUE TITLE
Installing plugin error?

### ISSUE THREAD

**Issue by hanzigs** [duydo/elasticsearch-analysis-vietnamese#72]
Followed these steps https://duydo.me/how-to-build-elasticsearch-vietnamese-analysis-plugin/

C:\ELK7.5.1\elasticsearch-7.5.1\bin>elasticsearch-plugin install C:\viet-plugin\vn-nlp-libraries\nlp-parent\elasticsearch-analysis-vietnamese\target\releases\elasticsearch-analysis-vietnamese-7.3.1.zip
-> Downloading C:\viet-plugin\vn-nlp-libraries\nlp-parent\elasticsearch-analysis-vietnamese\target\releases\elasticsearch-analysis-vietnamese-7.3.1.zip
Exception in thread "main" java.net.MalformedURLException: unknown protocol: c
        at java.base/java.net.URL.<init>(URL.java:651)
        at java.base/java.net.URL.<init>(URL.java:540)
        at java.base/java.net.URL.<init>(URL.java:487)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:376)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:279)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:230)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

any help please?

**Comment by harypham** [comment]
It's not a bug, just the way you installed the plugin.  It got me 30mins to figure out how to install it correctly
[correct way]:
elasticsearch-plugin install file:///C:/viet-plugin/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/target/releases/elasticsearch-analysis-vietnamese-7.3.1.zip

note: really poor documents in vietnamese
the way to install plugin for Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/plugins/6.8/plugin-management-custom-url.html
