### ISSUE TITLE
error when using char_filter: ["html_strip"] with vi_tokenizer (v7.5.2)

### ISSUE THREAD

**Issue by sLeeNguyen** [duydo/elasticsearch-analysis-vietnamese#89]
I got an error when analyzing documents with **_vi_tokenizer_** tokenizer and **_html_strip_** char filter

```
GET icu_vi_sample/_analyze
{
  "field": "introduce",
  "text":"<p>xin hãy giúp tôi</p>" 
}
```
This is my error
```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[5f466dceed54][172.25.0.2:9300][indices:admin/analyze[s]]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset; got startOffset=-1,endOffset=4"
  },
  "status": 400
}
```
```
elasticsearch_1  | {"type": "server", "timestamp": "2020-11-02T05:04:31,901Z", "level": "DEBUG", "component": "o.e.a.a.i.a.TransportAnalyzeAction", "cluster.name": "docker-cluster", "node.name": "5f466dceed54", "message": "null: failed to execute [org.elasticsearch.action.admin.indices.analyze.AnalyzeAction$Request@464d5861]", "cluster.uuid": "UaZEbuupRoG0FABqMP7KFA", "node.id": "vDNjCm37Sm2-AhewZ4IAAA" , 
elasticsearch_1  | "stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [5f466dceed54][172.25.0.2:9300][indices:admin/analyze[s]]",
elasticsearch_1  | "Caused by: java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset; got startOffset=-1,endOffset=4",
elasticsearch_1  | "at org.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl.setOffset(PackedTokenAttributeImpl.java:113) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]",
elasticsearch_1  | "at org.apache.lucene.analysis.vi.VietnameseTokenizer.incrementToken(VietnameseTokenizer.java:117) ~[?:?]",
elasticsearch_1  | "at org.apache.lucene.analysis.LowerCaseFilter.incrementToken(LowerCaseFilter.java:41) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]",
elasticsearch_1  | "at org.apache.lucene.analysis.miscellaneous.ASCIIFoldingFilter.incrementToken(ASCIIFoldingFilter.java:102) ~[lucene-analyzers-common-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:33]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:233) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:213) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:138) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:121) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:73) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:110) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) [elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) ~[elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:830) [?:?]"] }
```

This is my index setting
```
PUT /icu_vi_sample
{
  "settings": {
    "index": {
        "number_of_shards" : 1,
        "number_of_replicas" : 1,        
      "analysis": {
        "analyzer": {
          "my_analyzer": {
            "type": "custom",
            "tokenizer": "vi_tokenizer",
            "char_filter": [
              "html_strip"
              ],
            "filter":[
              "lowercase",
              "asciifolding"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "properties" : {
      "user" : {
        "type" : "text",
        "analyzer": "my_analyzer"
      },
      "introduce" : {
        "type" : "text",
        "analyzer" : "my_analyzer"
      }
    }            
  }
}
```
I build the Elasticsearch Vietnamese Analysis Plugin by myself for Elasticsearch-7.5.2.
Thank you!

**Comment by huylv69** [comment]
I got the same error with elasticsearch 7.8.1.

**Comment by anthony9981** [comment]
I got this error on elasticsearch 7.3.1 too
