### ISSUE TITLE
Occur error when install plugin elasticsearch-vietnamese-analyst-x.x.x.zip

### ISSUE THREAD

**Issue by lechihuy** [duydo/elasticsearch-analysis-vietnamese#99]
```
➜  elasticsearch-analysis-vietnamese git:(master) ✗ sudo elasticsearch-plugin install file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
Password:
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
-> Installing file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
-> Downloading file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
-> Failed installing file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
-> Rolling back file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
-> Rolled back file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip
Exception in thread "main" java.net.UnknownHostException: target
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:961)
	at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:923)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1018)
	at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1004)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:319)
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:425)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:448)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:329)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:251)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

I just build package and then install it, but a error occured. You may help me, please
Thanks

**Comment by LucDinhVan** [comment]
I think that problem is caused by incorrect path to plugin. 

try change: `file://target/releases/elasticsearch-analysis-vietnamese-7.10.1.zip` to `file:///path-to-file/elasticsearch-analysis-vietnamese-7.10.1.zip`.

Make sure path to plugin correct, in my case: `elasticsearch-plugin install file:///F:\setup\elasticsearch-analysis-vietnamese-7.3.1.zip`

Hope to help you.
